services:
  # Authentication Service
  auth_service_server:
    build: ./auth
    ports:
      - "8080:${AUTH_HTTP_PORT}"
    environment:
      - CONFIG_PATH=${AUTH_CONFIG_PATH}
      - HTTP_HOST=${AUTH_HTTP_HOST}
      - HTTP_PORT=${AUTH_HTTP_PORT}
      - POSTGRES_DB=${AUTH_POSTGRES_DB}
      - POSTGRES_USER=${AUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
      - POSTGRES_HOST=${AUTH_POSTGRES_HOST}
      - POSTGRES_PORT=${AUTH_POSTGRES_PORT}
      - REDIS_HOST=${AUTH_REDIS_HOST}
      - REDIS_PORT=${AUTH_REDIS_PORT}
      - REDIS_DB=${AUTH_REDIS_DB}
      - REDIS_PASSWORD=${AUTH_REDIS_PASSWORD}
    volumes:
      - ./auth/config:/app/config:ro
      - ./auth/private.pem:/app/keys/private.pem:ro
      - ./auth/public.pem:/app/keys/public.pem:ro
    depends_on:
      auth_service_postgres:
        condition: service_healthy
      auth_service_redis:
        condition: service_healthy

  # Auth service postgres
  auth_service_postgres:
    image: postgres:18-alpine
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=${AUTH_POSTGRES_DB}
      - POSTGRES_USER=${AUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
    ports:
      - "${AUTH_POSTGRES_PORT}:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_POSTGRES_USER} -d ${AUTH_POSTGRES_DB}"]
      interval: 5s
      retries: 5

  # Auth service redis
  auth_service_redis:
    image: redis:8-alpine
    command: ["redis-server", "--requirepass", "${AUTH_REDIS_PASSWORD}"]
    ports:
      - "${AUTH_REDIS_PORT}:6379"
    volumes:
      - auth_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${AUTH_REDIS_PASSWORD}", "ping"]
      interval: 5s
      retries: 5

volumes:
  auth_postgres_data: {}
  auth_redis_data: {}