env: "local"

postgres:
  sslmode: "disable"
  timezone: Asia/Shanghai

jwt:
  private_key_path: "/app/keys/private.pem"
  public_key_path: "/app/keys/public.pem"
  issuer: "auth"
  access_ttl: "15m"
  refresh_ttl: "90d"

redis:
  max_retries: 5
  dial_timeout: 10
  read_timeout: 5
  write_timeout: 5
