env: "local"

http_server: 
  address: "localhost"
  port: "8080"

postgres:
  host: "localhost"
  port: 5432
  name: "auth_db"
  user: "postgres"
  password: "9if-6p0vNpzV"
  sslmode: "disable"
  timezone: Asia/Shanghai